jack-hermanson/cis200

- main/modules/advisory/routes.py
- main/web/templates/advisory/hr.html
Created the HR page in Advisory.
> Add hr page to advisory

- main/web/templates/social/health-foods.html
Implemented template into health food page so that when I am given information I can add it in.
> Implement Health Food Template

- main/web/templates/economic/homelessness-in-colorado.html
> Updated text/grammar on Homelessness page

- main/web/templates/social/bias-in-the-news.html
> add video to bias in the news and update grammar

- main/web/templates/economic/affordable-housing.html
> Add text references affordable housing

- main/web/templates/advisory/project-management.html
- main/web/templates/economic/affordable-housing.html
> Updated pm page

- main/web/templates/advisory/learning-support-001.html
- main/web/templates/base.html
> Add resources link in footer

- main/web/templates/about/mission-and-vision.html
- main/web/templates/advisory/learning-support-004.html
> Corrected text in Mission page, as well as LS 004.

- main/web/templates/advisory/marketing.html
- main/web/templates/base.html
> Updated marketing page

- main/web/templates/about/index.html
> update home page text

- main/modules/advisory/routes.py
- main/web/templates/advisory/index.html
- main/web/templates/advisory/multimedia.html
> add multimedia page

- main/__init__.py
- main/config.py
- main/modules/contact/routes.py
- main/utils/ContactMessage.py
- requirements.txt
> Contact form

- main/web/templates/advisory/index.html
> Removed title headers and edited text for consistent card sizes

- main/modules/advisory/routes.py
- main/web/templates/advisory/index.html
- main/web/templates/advisory/is-team.html
> Added route to/and IS-team page

- main/web/templates/social/social-isolation.html
Added text to the social isolation page and updated the video URL
closes #154 
closes #187
> Updated social-isolation.html

- main/web/templates/social/worksite-wellness.html
added text to worksite wellness page
closes #156
> Added text to worksite-wellness.html

- main/web/templates/advisory/hr.html
> add new hr video

- main/web/templates/social/social-isolation.html
> italicize journal names

- main/web/templates/advisory/learning-support-001.html
> remove card from learning support

- main/web/templates/economic/index.html
- main/web/templates/environmental/index.html
> Card image sizes

- main/web/templates/main/index.html
updated home page of website to be in line with the "information is power" domain name
closes #210
> Updated index.html

- main/web/templates/main/projects.html
added text to featured projects page
closes #216
> Update featured projects page

- main/web/templates/environmental/index.html
added text and changed sort order of cards
closes #213
> Updated environmental index page

- main/web/templates/economic/index.html
updated text and card order on economic index page
closes #214
> Update economic index page

- main/web/templates/projects/health-foods.html
added text to the health foods page
closes #152
> Added text health foods

- main/web/templates/economic/index.html
- main/web/templates/social/index.html
updated social sustainability page
- updated h1 text
- added page description
- updated text per card to be similar in length
- re-arranged cards in rows to group similar projects
closes #145
> updated social index.html page

- main/web/templates/projects/csu-sustainability.html
updated/edited text on CSU sustainability page
closes #150
> Updated csu-sustainability.html

- main/web/templates/projects/online-scamming.html
added text to online-scamming.html
closes #153
> added text to online-scamming.html

- main/web/templates/projects/cookies.html
added text to cookies page
closes #159
> added-text-to-cookies-html

- main/web/templates/projects/information-privacy.html
added text to information-privacy.html page
closes #155
> added-text-information-privacy.html

- main/web/templates/economic/index.html
- main/web/templates/projects/health-foods.html
- main/web/templates/projects/wells-fargo-scandal.html
added text to Wells Fargo Scandal page
closes #146
> Updated wells-fargo-scandal.html

- main/web/templates/social/index.html
fixed spelling of Harman and some other text that needed clean up
closes #227
> Updated text on social sustainability home page

- main/web/templates/meet-the-teams/index.html
updated meet the teams page to re-arrange content and clean up card descriptions
> Update index.html Meet the Teams

- main/web/templates/meet-the-teams/multimedia.html
- main/web/templates/social/index.html
added content to multimedia page
- added YT video link
- added description and student quotes
closes #212
> Add content to multimedia.html
